version: '3.8'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "postgresvd"
      POSTGRES_DB: visualdynamics
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - ./scripts/create-directus-database.sh:/docker-entrypoint-initdb.d/create-directus-database.sh

  redis:
    image: redis:alpine
    volumes:
      - ${REDIS_DATA_PATH}:/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: sh -c "yarn prisma generate && yarn dev"
    env_file: .env.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${VISUALDYNAMICS_URL}`)"
      - "traefik.http.routers.client.service=client"
      - "traefik.http.services.client.loadbalancer.server.port=3001"
    links:
      - database
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

  server:
    build: ./server
    command: flask run --host=0.0.0.0 --port=3002
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLASK_DEBUG=${DEBUG}
      - MAILER_URL=client:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${VISUALDYNAMICS_URL}`) && PathPrefix(`/server`)"
      - "traefik.http.routers.server.service=server"
      - "traefik.http.services.server.loadbalancer.server.port=3002"
    links:
      - redis
    volumes:
      - ./server:/var/www/server
      - ${VISUALDYNAMICS_USER_SIMULATIONS_PATH}:/var/www/VDfiles

  worker:
    build: 
      context: ./server
      dockerfile: Dockerfile.worker
    command: celery -A server.celery_tasks worker --concurrency=1
    volumes:
      - ./server:/var/www/server
      - ${VISUALDYNAMICS_USER_SIMULATIONS_PATH}:/var/www/VDfiles
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLASK_DEBUG=${DEBUG}
    links:
      - redis

  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      # - "--metrics.prometheus=true"
      # - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # - "--metrics.prometheus.addrouterslabels=true"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.docker.exposedByDefault=false"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.letsencrypt.acme.email=greenfrog@email.com"  # replace with your email
      # - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      # - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      # - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # - "traefik.http.routers.traefik.tls=true"
      # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.traefik.tls.domains[0].main=${TRAEFIK_URL}"
      # - "traefik.http.routers.traefik.tls.domains[0].sans=*.${TRAEFIK_URL}"
      # - "traefik.http.routers.traefik.entryPoints=websecure"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme:/acme
      - ./traefik/logs:/logs
    ports:
      - "80:80"
      - "443:443"

  directus:
    image: directus/directus:latest
    volumes:
      - ./uploads:/directus/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directus.rule=Host(`${VISUALDYNAMICS_URL}`) && PathPrefix(`/directus{regex:$$|/.*}`)"
      - "traefik.http.routers.directus.service=directus"
      - "traefik.http.routers.directus.middlewares=directus-strip-prefix"
      - "traefik.http.services.directus.loadbalancer.server.port=8055"
      - "traefik.http.middlewares.directus-strip-prefix.stripprefix.prefixes=/directus"
      - "traefik.http.middlewares.directus-strip-prefix.stripprefix.forceSlash=false"
    environment:
      KEY: 'replace-with-random-value'
      SECRET: 'replace-with-random-value'
      PUBLIC_URL: 'http://${VISUALDYNAMICS_URL}/directus'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'admin'
      DB_CLIENT: 'pg'
      DB_CONNECTION_STRING: ${DIRECTUS_DATABASE_URL}
      WEBSOCKETS_ENABLED: true
